name: Build and Test

on:
  workflow_dispatch:
  push:
    branches:
    - "*"
    paths-ignore:
    - '.gitattributes'
    - '.gitignore'
    - 'LICENSE'
    - 'README.md'
    - '.vscode/**'
    - '.devcontainer/**'
    - '.assets/**'
  pull_request:
    branches:
    - "*"
    paths-ignore:
    - '.gitattributes'
    - '.gitignore'
    - 'LICENSE'
    - 'README.md'
    - '.vscode/**'
    - '.devcontainer/**'
    - '.assets/**'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      YAEGI_VERSION: v0.13.0
      GOPATH: ${{ github.workspace }}/go
      CGO_ENABLED: 0
    defaults:
      run:
        working-directory: ${{ github.workspace }}/go/src/github.com/${{ github.repository }}

    steps:
    - uses: actions/checkout@v4
      with:
        path: go/src/github.com/${{ github.repository }}
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: 'go/src/github.com/${{ github.repository }}/go.mod'
        cache-dependency-path: |
          'go/src/github.com/${{ github.repository }}/go.sum'

    - name: Build Cloudflare IPs
      run: bash updateCFIps.sh ci

    - name: Setup GOPATH
      run: go env -w GOPATH=${{ github.workspace }}/go

    - name: Install Yaegi ${{ env.YAEGI_VERSION }}
      run: curl -sfL https://raw.githubusercontent.com/traefik/yaegi/master/install.sh | bash -s -- -b ${{ github.workspace }}/go/bin ${YAEGI_VERSION}
      # working-directory: ${{ github.workspace }}

    - name: Test Code
      run: go test -race -coverprofile=coverage.txt -covermode=atomic ./*_test.go
      env:
        CGO_ENABLED: 1

    - name: Run tests with Yaegi
      run: ${{ github.workspace }}/go/bin/yaegi test .

    - name: Test With Traefik
      run: bash ./test/test.sh

    - name: Upload log artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: logs
        if-no-files-found: error
        path: ${{ github.workspace }}/go/src/github.com/${{ github.repository }}/test/output/*
        retention-days: 30
